// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwatcfwdagliujicrfvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3YXRjZndkYWdsaXVqaWNyZnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzAzMDgsImV4cCI6MjA3MzQ0NjMwOH0.tfEpfi9ex7RuqjkcHZfiIOXqXh3Y8HyRWfZqyp9aNCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});